spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 3000